[package]
name = "caduceus-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
axum = { version = "0.8.4", features = ["ws", "multipart", "query"] }
axum-extra = "0.10.1"
tokio = { version = "1.47.1", features = ["full"] }
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.6", features = ["fs", "cors", "trace"] }

# Serialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
bson = { version = "2.15.0", features = ["chrono-0_4"] }

# Database
mongodb = "3.2.5"

# Authentication
jsonwebtoken = "9.3.1"
bcrypt = "0.17.1"

# Configuration
config = "0.15.15"

# Error handling
anyhow = "1.0.99"
thiserror = "2.0.16"

# Time
chrono = { version = "0.4.41", features = ["serde"] }

# Logging
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

# Validation
validator = { version = "0.20.0", features = ["derive"] }

# Regex
regex = "1.11.2"

[dev-dependencies]
tokio-test = "0.4.4"
axum-test = "18.0.1"
httpmock = "0.7.0"
mockall = "0.13.1"
serial_test = "3.2.0"
