[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}
dotenv = "0.15.0"
axum = "0.8.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.6.1", features = ["add-extension", "trace"] }

[dependencies.mongodb]
version = "3.2.4"
