import { NavBar } from "@/components/roots/NavBar";
import { Providers } from "@/components/roots/Providers";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-background font-sans text-foreground antialiased`}>
        <Providers>
          <div className="relative h-screen">
            <NavBar />
            {children}
            <footer>
              <p className="text-sm text-muted-foreground">
                © {new Date().getFullYear()} Your Company Name
              </p>
            </footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
